---
- include_vars: zone.yml

- name: 'get existing pattern for {{ zone.name }}'
  set_fact:
    zpat1: '{{ zpatterns.stdout_lines | map("regex_search","^"+zone.name+" [^ ]*") | select("string") | list }}'
- name: 'get existing pattern for {{ zone.name }} - end'
  set_fact:
    zpat: '{% if zpat1 | count > 0 %}{{ zpat1[0] | regex_replace("^.* ([^ ]*)$","\1") }}{% endif %}'

- name: 'delete zone {{ zone.name }}'
  command: '{{ nsd_bin }}-control delzone {{ zone.name }}'
  when: 'zpat | length > 0 and zone.pattern | length > 0 and zpat != zone.pattern'
  register: zdel
  notify: reconfig nsd

- name: 'add zone {{ zone.name }}'
  command: '{{ nsd_bin }}-control addzone {{ zone.name }} {{ zone.pattern }}'
  when: 'zone.pattern | length > 0 and ( zdel.changed or zpat | length == 0 )
    and zone.pattern in nsd_patterns_list'
  register: zadd
  notify: reconfig nsd

- debug:
   msg: 'Zone {{ zone.name }} modifiee ou ajoutee'
  when: 'zone.pattern and zone.pattern in nsd_patterns_list and zadd.changed | default(False)'
